---
- name: Localizes the Ubuntu image for K8S
  hosts: default
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    # Uncomment for smoke test
    # - name: SSH connection test
    #   ansible.builtin.include_role:
    #     name: display_time
    - name: Set up OS settings
      ansible.builtin.include_role:
        name: node
    - name: Set up containerd
      ansible.builtin.include_role:
        name: containerd
    - name: Set up AWS CLI
      ansible.builtin.include_role:
        name: awscli
    - name: Set up Cilium CLI
      ansible.builtin.include_role:
        name: ciliumcli
    - name: Set up Kubernetes
      ansible.builtin.include_role:
        name: kubernetes
