- name: Ensure apt keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: >-
      deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu
      {{ ansible_lsb.codename }} stable
    state: present

- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io
    update_cache: true
    state: present

- name: Copy in containerd config file
  ansible.builtin.copy:
    src: etc/containerd/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "0644"

- name: Start containerd service
  ansible.builtin.systemd:
    name: containerd
    daemon_reload: true
    enabled: true
    state: restarted
