---
- name: Ensure apt keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Kubernetes’s official GPG key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key
    keyring: "{{ kubernetes_repo_key }}"
    state: present

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    filename: kubernetes
    repo: >-
      deb [signed-by={{ kubernetes_repo_key }}] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /
    state: present

- name: Install Kubernetes
  ansible.builtin.apt:
    name: "{{ kubernetes_packages }}"
    update_cache: true
    state: present

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ kubernetes_packages }}"

- name: Configure hosts
  block:
    - name: Create update-hosts script
      ansible.builtin.template:
        src: "{{ kubernetes_update_hosts_script_path }}.j2"
        dest: "/{{ kubernetes_update_hosts_script_path }}"
        owner: root
        group: root
        mode: "0740"

    - name: Create cloud-init config for dynamic hosts entry
      ansible.builtin.template:
        src: "{{ kubernetes_cloud_init_dynamic_hosts_config_path }}.j2"
        dest: "/{{ kubernetes_cloud_init_dynamic_hosts_config_path }}"
        owner: root
        group: root
        mode: "0644"

- name: Create kubeadm-config file
  ansible.builtin.template:
    src: "{{ kubernetes_kubeadm_config_path }}.j2"
    dest: "/{{ kubernetes_kubeadm_config_path }}"
    owner: root
    group: root
    mode: "0600"
